# Generated by Django 5.2.17 on 2026-10-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='score',
            name='allowed_score',
        ),
        migrations.AddField(
            model_name='classroom',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[(1, '1e leerjaar'), (2, '2e leerjaar'), (3, '3e leerjaar'), (4, '4e leerjaar'), (5, '5e leerjaar'), (6, '6e leerjaar'), (7, '7e leerjaar')], null=True, verbose_name='Leerjaar'),
        ),
        migrations.AddField(
            model_name='goal',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[(1, '1e leerjaar'), (2, '2e leerjaar'), (3, '3e leerjaar'), (4, '4e leerjaar'), (5, '5e leerjaar'), (6, '6e leerjaar'), (7, '7e leerjaar')], null=True, verbose_name='Leerjaar'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[(1, '1e leerjaar'), (2, '2e leerjaar'), (3, '3e leerjaar'), (4, '4e leerjaar'), (5, '5e leerjaar'), (6, '6e leerjaar'), (7, '7e leerjaar')], null=True, verbose_name='Leerjaar'),
        ),
        migrations.AddField(
            model_name='score',
            name='status',
            field=models.CharField(choices=[('scored', 'Beoordeeld'), ('absent', 'Afwezig')], default='scored', max_length=10),
        ),
        migrations.AlterField(
            model_name='score',
            name='value',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (20, '20'), (40, '40'), (60, '60'), (80, '80')], null=True),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'scored'), ('value__in', [0, 20, 40, 60, 80]), ('value__isnull', False)), models.Q(('status', 'absent'), ('value__isnull', True)), _connector='OR'), name='valid_score_or_absence'),
        ),
    ]
