# Generated by Django 5.2.17 on 2026-10-04 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_backfill_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Studierichting')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='study_direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='evaluations.studydirection', verbose_name='Studierichting'),
        ),
        migrations.AddField(
            model_name='subject',
            name='study_directions',
            field=models.ManyToManyField(blank=True, to='evaluations.studydirection', verbose_name='Studierichtingen'),
        ),
        migrations.AddConstraint(
            model_name='studydirection',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_owner_direction'),
        ),
    ]
