# Generated by Django 5.2.17 on 2026-10-04 12:26

import django.db.models.deletion
from django.db import migrations, models


def preserve_and_convert(apps, schema_editor):
    Goal = apps.get_model('evaluations', 'Goal')
    alias = schema_editor.connection.alias
    for goal in Goal.objects.using(alias).select_related('year', 'subject'):
        classes = list(goal.classrooms.all())
        directions = {c.study_direction_id for c in classes if c.owner_id == goal.owner_id and c.study_direction_id}
        if not directions:
            directions = set(goal.subject.study_directions.filter(owner_id=goal.owner_id).values_list('pk', flat=True))
        goal.legacy_context = {'school_year_id': goal.year_id, 'school_year': goal.year.name,
            'subject_id': goal.subject_id, 'subject': goal.subject.name, 'grade': goal.grade,
            'classroom_ids': [c.pk for c in classes], 'direction_ids': sorted(directions)}
        goal.study_direction_id = next(iter(directions)) if len(directions) == 1 else None
        goal.stage = min(3, (goal.grade + 1) // 2) if goal.grade in range(1, 8) else None
        goal.save(using=alias, update_fields=['legacy_context', 'study_direction', 'stage'])


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_backfill_directions'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='legacy_context',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='goal',
            name='stage',
            field=models.PositiveSmallIntegerField(choices=[(1, '1e graad'), (2, '2e graad'), (3, '3e graad (inclusief 7e leerjaar)')], null=True, verbose_name='Graad'),
        ),
        migrations.AddField(
            model_name='goal',
            name='study_direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='evaluations.studydirection', verbose_name='Studierichting'),
        ),
        migrations.RunPython(preserve_and_convert),
        migrations.RemoveField(model_name='goal', name='classrooms'),
        migrations.RemoveField(model_name='goal', name='grade'),
        migrations.RemoveField(model_name='goal', name='subject'),
        migrations.RemoveField(model_name='goal', name='year'),
    ]
