# Generated by Django 5.2.17 on 2026-10-04 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0006_remove_goal_classrooms_remove_goal_grade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['study_direction__name', 'name', 'pk']},
        ),
    ]
