# Generated by Django 5.2.17 on 2026-10-05 13:59

import django.db.models.deletion
from django.db import migrations, models


def link_existing(apps, schema_editor):
    Point = apps.get_model('evaluations', 'Point')
    LessonPoint = apps.get_model('evaluations', 'LessonPoint')
    catalog = {}
    for point in Point.objects.using(schema_editor.connection.alias).all():
        catalog.setdefault((point.goal_id, point.title), []).append(point)
    for snapshot in LessonPoint.objects.using(schema_editor.connection.alias).select_related('goal').iterator():
        candidates = catalog.get((snapshot.goal.source_id, snapshot.title), [])
        exact = [p for p in candidates if p.position == snapshot.position]
        match = exact if len(exact) == 1 else candidates
        if len(match) == 1:
            snapshot.source_point_id = match[0].pk
            snapshot.save(update_fields=['source_point'], using=schema_editor.connection.alias)


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0007_alter_classroom_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonpoint',
            name='is_direct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessonpoint',
            name='source_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluations.point'),
        ),
        migrations.RunPython(link_existing, migrations.RunPython.noop),
    ]
