# Generated by Django 5.2.17 on 2026-10-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_export',
            field=models.BooleanField(default=True, verbose_name='Excel-export van eigen evaluaties'),
        ),
    ]
