# Generated by Django 5.2.17 on 2026-10-04 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_can_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='goal_defaults',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='ui_colors',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='view_all_teachers',
            field=models.BooleanField(default=True, verbose_name='Inhoud van alle leerkrachten bekijken'),
        ),
        migrations.AddField(
            model_name='user',
            name='visible_teachers',
            field=models.ManyToManyField(blank=True, related_name='authorized_viewers', to=settings.AUTH_USER_MODEL, verbose_name='Inhoud van deze leerkrachten bekijken'),
        ),
    ]
